"""initial schema

Revision ID: 614047abe21d
Revises:
Create Date: 2026-09-20 15:57:14.391465
"""

from alembic import op
import sqlalchemy as sa


revision = "614047abe21d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rarity", sa.String(length=32), nullable=False),
        sa.Column("origin_galaxy", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "auctions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("starting_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("highest_bidder_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "ACTIVE", "FINISHED", name="auction_status"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_auctions_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["highest_bidder_id"],
            ["users.id"],
            name=op.f("fk_auctions_highest_bidder_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auctions")),
    )
    op.create_index(
        op.f("ix_auctions_artifact_id"), "auctions", ["artifact_id"], unique=False
    )
    op.create_index(op.f("ix_auctions_status"), "auctions", ["status"], unique=False)
    op.create_table(
        "bids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["auction_id"], ["auctions.id"], name=op.f("fk_bids_auction_id_auctions")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bids_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bids")),
    )
    op.create_index(
        "ix_bids_auction_amount", "bids", ["auction_id", "amount"], unique=False
    )
    op.create_index(op.f("ix_bids_user_id"), "bids", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bids_user_id"), table_name="bids")
    op.drop_index("ix_bids_auction_amount", table_name="bids")
    op.drop_table("bids")
    op.drop_index(op.f("ix_auctions_status"), table_name="auctions")
    op.drop_index(op.f("ix_auctions_artifact_id"), table_name="auctions")
    op.drop_table("auctions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
